name: flutter_final
description: A new Flutter project.

# Prevent the package from being accidentally published to pub.dev
publish_to: 'none'

# Define the version and build number for your application
version: 1.0.0+1

# Specify the Flutter SDK environment constraints
environment:
  sdk: '>=3.5.3 <4.0.0'

# Dependencies required for the project
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Define the asset paths used in the project
  assets:
    - assets/images/logo_pmi.png
    - assets/images/location1.png
    - assets/images/location2.png
    - assets/images/RSI Harapan Anda Tegal.png
    - assets/images/RS Mitra Keluarga.png
    - assets/images/loogo bd.png
    - assets/images/virtual_assistant.png
    - assets/images/cek_kondisi.png
    - assets/images/bg donor.jpeg
    - assets/images/bg donor2.jpeg
    - assets/images/bg donor3.jpeg
    - assets/images/bg donor4.jpeg
    - assets/images/bg manfaat.png
    - assets/images/bg profile.png
    - assets/images/pmi-tegal.png

